name: action-rnd
on: 
  push:
    branches:
      - developer
jobs:
  uat:
    runs-on: ["self-hosted", "ubuntu"]
    # environment:
    #   name: uat
    name: developer-branch-deployment
    steps:
      - run: |
          mkdir my_working_dir
      - uses: actions/checkout@v4.1.7
        with:
          path: "./my_working_dir"
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.9'
      - run: |
          pwd
      - run: |
          pip install virtualenv
          python -m venv ./my_working_dir/env 
          ./my_working_dir/env/bin/pip install scikit-learn
          ./my_working_dir/env/bin/pip install fastapi
      # - run: |
      #     rm -rf ./my_working_dir
      - uses: jfrog/setup-jfrog-cli@v4.4.1
        with:
          version: 2.67.0
        env:
          JF_URL: ${{secrets.JF_URL}}
          JF_ACCESS_TOKEN: ${{secrets.JF_ACCESS_TOKEN}}
      - run: |
          jf rt u --archive zip  my_working_dir/application/requirements.txt testartifactsrepo/frontend
          
  
    

  
    
