name: checks-rnd
on: 
  pull_request:
    branches:
      - developer
jobs:
  any:
    permissions:
      contents: read
      packages: read
      statuses: write  
    runs-on: ubuntu-latest #["self-hosted", "ubuntu"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.1.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_RUFF: true

      
