name: demo-workflow
on: workflow_dispatch
jobs:
  dmeo:
    runs-on: [self-hosted, app_service]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.1.1
        with: 
          python-version: 3.9.19
      - run: python ./app.py
    
