name: jfrog-rnd
on: 
  push:
    branches:
      - developer
jobs:
  uat:
    runs-on: ["self-hosted", "ubuntu"]
    steps:
      - uses: jfrog/setup-jfrog-cli@v4.4.1
        with:
          version: 2.67.0
        env:
          JF_URL: ${{secrets.JF_URL}}
          JF_ACCESS_TOKEN: ${{secrets.JF_ACCESS_TOKEN}}
      # - run: |
      #     jf rt dl  testartifactsrepo/frontend:34  .
      # - run: |
      #     ls -al
      - run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/actions/variables
      # - run: |
      #     gh api \
      #       --method PATCH \
      #       -H "Accept: application/vnd.github+json" \
      #       /repos/OWNER/REPO/actions/variables/NAME \
      #        -f "name=USERNAME" -f "value=octocat"
          
